introduced how arg in device_finalizer_fn
HPCToolkit/hpctoolkit pull request #372
Opened 2021-01-21 03:49 UTC by dejangrubisic

Adaptation to Keren's change of finalizer function, and deleting gpu_operation_channel_set_await as unnecessery

2021-01-29 21:44 UTC, dejangrubisic commented
This should improve tracing speed. I have checked out Lagos and the realtime was 11.969s while the current develop is 17.318s.
Produced database looks as expected in traceviewer.

2021-01-29 22:33 UTC, Jokeren commented
I remembered it is ~11.9s vs ~14.0s something.

Please attach the results with the following three configurations.

- develop with -t
- this commit with -t
- this commit without -t

2021-01-29 23:44 UTC, dejangrubisic commented
This time I got:
    develop with -t -> 10.457s
    this commit with -t -> 8.727s
    this commit without -t -> 7.524s

2021-01-30 00:19 UTC, jmellorcrummey reviewed
I don't understand what this commit means. There aren't any calls to gpu_operation_channel_set_await anymore. Are threads just spinning hard all the time? Or, do they sleep at some point?

2021-01-30 00:31 UTC, dejangrubisic commented
This commit:
1. Contains a change in definitions of gpu_trace_fini (adding how arg),
2. In current develop gpu_operation_channel_set_await was already removed from the loops. This commit removes it after the loop, which resulted in better performance.
3. Moves control knob_init after hpcrun_registered_sources_init, as otherwise, it wouldn't pick user-defined knobs

2021-01-30 03:34 UTC, Jokeren approved these changes

2021-01-30 03:34 UTC, Jokeren commented on src/tool/hpcrun/sample_sources_registered.c
> +  control_knob_init();
I am ok with all the changes.

2021-02-02 00:54 UTC, jmellorcrummey requested changes
I don't think that control_knob_init should be called from sample_sources_init. Why do you think it should?

Why did you add an argument to gpu_trace_fini if it is always called with a 0 for how. It should never be passed a number. The number should be replaced with the named constant from monitor.h.

Why can a call to channel_set_await just be deleted?

2021-02-03 02:45 UTC, dejangrubisic commented
I instead of hard-spinning on each channel I inserted nanosleep() of for total sleep of 5us. Compared with hard-spinning user time is much lower.

            Hard-spinning  Nanosleep
real       0.733s               0.763s
user      0.732s               0.312s  
sys        0.410s               0.407s

2021-02-03 03:16 UTC, Jokeren requested changes

2021-02-03 03:16 UTC, Jokeren commented on src/tool/hpcrun/gpu/gpu-trace.c
> +#define TRACE_CHANNEL_SLEEP 5000000 // in ns
Isn't it 5ms instead of 5us?

2021-02-03 06:44 UTC, jmellorcrummey reviewed
I am accepting the changes but I am changing the sleep time to half a second 50M ns. I don't think that we need to be checking for updates 200  times per second. 20 times a second should be plenty. Even delaying a half second might be fine.

2021-02-03 06:47 UTC, merged

2021-02-03 18:24 UTC, dejangrubisic commented on src/tool/hpcrun/gpu/gpu-trace.c
> +#define TRACE_CHANNEL_SLEEP 5000000 // in ns
Yes it is 5ms, my fault